- hosts: dev
  become: true
  user: vagrant
  pre_tasks:
    - name: Yum update
      yum: name=* state=latest exclude=kernel*

    - name: policycoreutils-pythonをインストール
      yum: 
        name: policycoreutils-python
        state: latest

    - name: SELinuxを無効化
      selinux: state=disabled
  roles:
    - packages
    - zsh
    - vim
    - firewall
    - git
    - fonts
    - phantomjs
    - docker-engine
    - rbenv
    - ruby_reference
  tasks:
    - name: SELinuxの有効化
      selinux: state=enforcing policy=targeted

