- name: ソースの取得
  git:
    repo: https://github.com/vim/vim.git
    dest: /tmp/vim

- name: コンパイルオプションの設定
  shell: |
    ./configure \
    --enable-fail-if-missing \
    --enable-fontset \
    --enable-luainterp \
    --enable-multibyte \
    --enable-perlinterp \
    --enable-python3interp \
    --enable-pythoninterp \
    --enable-rubyinterp \
    --enable-xim \
    --with-features=huge \
  args:
    chdir: /tmp/vim

- name: インストール
  make: 
    chdir: /tmp/vim
    target: install

- name: dotfilesを取得
  become: no
  git:
    repo: https://github.com/shimgo/dotfiles.git
    dest: ~/dotfiles

- name: dotfilesを配置
  become: no
  make: 
    chdir: ~/dotfiles
    target: deploy
