- name: ソースの取得
  git:
    repo: https://github.com/vim/vim.git
    dest: /tmp/vim

- name: コンパイルオプションの設定
  shell: |
    ./configure \
    --enable-fail-if-missing \
    --enable-fontset \
    --enable-luainterp \
    --enable-multibyte \
    --enable-perlinterp \
    --enable-python3interp \
    --enable-pythoninterp \
    --enable-rubyinterp \
    --enable-xim \
    --with-features=huge \
  args:
    chdir: /tmp/vim

- name: maek
  make: 
    chdir: /tmp/vim
    target: install
