version: "2"
services:
  dev:
    container_name: dev
    hostname: dev
    restart: always
    image: devenv
    environment:
      RAILS_ENV: development
      MYSQL_ROOT_PASSWORD: 'pass'
      DATABASE_URL_DEVELOPMENT: mysql2://root:pass@mysql:3306
      DATABASE_URL_TEST: mysql2://root:pass@mysql:3306
      DATABASE_URL_PRODUCTION: mysql2://root:pass@mysql:3306
      SECRET_KEY_BASE: hogehoge
    ports:
      - '9292:9292'
      - '3001:3000'
    tty: true
    volumes:
      - dev_home:/home/developer

volumes:
  dev_home:
    external: true
